### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by That-Dude** [act28/pia-openvpn-proxy#18]
I'm sure that I'm doing something silly but I just cannot get get this docker to start, do you have any pointers?

```
>docker-compose up
Starting opt_vpn_proxy_1 ... done
Attaching to opt_vpn_proxy_1
vpn_proxy_1  | standard_init_linux.go:228: exec user process caused: exec format error
```
```
>cat docker-compose.yaml

version: "3.8"
services:
  vpn_proxy:
    image: docker.io/act28/pia-openvpn-proxy
    cap_add:
      - MKNOD
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 209.222.18.218
      - 209.222.18.222
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VPN_PROXY_CONFIG}:/config
    # if using wireguard, uncomment the next line
    privileged: true
    environment:
      - VPN_PROTOCOL=${VPN_PROTOCOL}
      - REGION=${REGION}
      - USERNAME=${PIA_USERNAME}
      - PASSWORD=${PIA_PASSWORD}
      - UID=${UID}
      - GID=${GID}
      - LOCAL_NETWORK=${LOCAL_NET}/24
    networks:
      - vpn_proxy
    ports:
      - 8118:8118
    restart: always

networks:
  vpn_proxy:
```

```
>cat .env 

VPN_PROXY_CONFIG="/opt/pia-openvpn-proxy"
VPN_PROTOCOL="wireguard"
REGION="swiss"
PIA_USERNAME="XXXXXXXX"
PIA_PASSWORD="XXXXXXXX"
UID="1000"
GID="1000"
LOCAL_NET="192.168.1.0"
```
